Budget.Web/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Budget.Web.Controllers.Common;
using Budget.Web.Helpers.Converters;

namespace Budget.Web.Controllers
{
    public class EmployeesController : BaseController
    {
        //
        // GET: /Employees/

        public ActionResult Index()
        {
            var employes = GetBudgetClient().Data.Employes.GetAll();

            var model = employes.Select(m => m.ToModel());

            return View(model);
        }

        //
        // GET: /Employees/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Employees/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Employees/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /Employees/Edit/5
 
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Employees/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Employees/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Employees/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Budget.Web/Controllers/FinancialCentersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Budget.Services.BudgetModel;
using Budget.Services.BudgetServices.DataProviderContracts;
using Budget.Services.BudgetServices.DataProviders;
using Budget.Web.Controllers.Common;
using Budget.Web.Models;
using EmitMapper;
using Budget.Web.Helpers.Converters;

namespace Budget.Web.Controllers
{
    public class FinancialCentersController : BaseController
    {
        public ActionResult Index()
        {
            var financialCenters = GetBudgetClient().Data.FinancialCenters.GetAll();

            if (financialCenters == null || !financialCenters.Any())
            {
                return View("FinancialCentersNotFound");
            }

            var model = financialCenters.Select(m => m.ToModel());

            return View(model);
        }

        //
        // GET: /FinancialCenters/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /FinancialCenters/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /FinancialCenters/Create

        [HttpPost]
        public ActionResult Create(FinancialCenterModel model)
        {
            try
            {
                GetBudgetClient().Data.FinancialCenters.Insert(model.ToObj());

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                //ViewBag.Error = "Create faild: " + ex. 
                return View();
            }
        }
        
        //
        // GET: /FinancialCenters/Edit/5
 
        public ActionResult Edit(int id)
        {
            var model = GetBudgetClient().Data.FinancialCenters.Get(id).ToModel();
            return View(model);
        }

        //
        // POST: /FinancialCenters/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FinancialCenterModel model)
        {
            try
            {
                GetBudgetClient().Data.FinancialCenters.Update(model.ToObj());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /FinancialCenters/Delete/5
 
        public ActionResult Delete(int id)
        {
            var model = GetBudgetClient().Data.FinancialCenters.Get(id).ToModel();
            return View(model);
        }

        //
        // POST: /FinancialCenters/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FinancialCenterModel model)
        {
            try
            {
                GetBudgetClient().Data.FinancialCenters.Delete(id);
                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Budget.Web/Views/Shared/CustomErrorView.cshtml
@{
    ViewBag.Title = "Помилка у додатку";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h2 class="text-error">Виникла помилка у додатку</h2>
</div>
<div class="row-fluid">
    <div class="span6">
        <article>
            <p class="lead">@ViewBag.Error</p>
            <p>@ViewBag.StackTrace</p>
        </article>
    </div>
</div>

Budget.Web/Views/Shared/_BudgetLayout.cshtml
@using Budget.Web.Helpers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section JavaScript
{
    @RenderSection("JavaScript", false)
}

<div class="row-fluid">
    <div class="tabs-left span2">
        <ul class="nav nav-tabs">
            <li class="@Html.SetMenuItemClass("Index", "ActiveBudgets")">
                <a href="@Url.Action("Index", "ActiveBudgets")">Активні бюджети</a>
            </li>
            <li class=@Html.SetMenuItemClass("Index", "ApprovalBudgets")>
                <a href="@Url.Action("Index", "ApprovalBudgets")">Затвердженні бюджети</a>
            </li>
            <li class=@Html.SetMenuItemClass("Index", "BudgetArchive")>
                <a href="@Url.Action("Index", "BudgetArchive")">Бюджетний архів</a>
            </li>
            <li class=@Html.SetMenuItemClass("Index", "WaitApproveBudgets")>
                <a href="@Url.Action("Index", "WaitApproveBudgets")">Проекти на затвердження</a>
            </li>
        </ul>
    </div>
    <div class="span10">
        @RenderBody()
    </div>
</div>

Budget.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css" media="screen"/>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/BudgetSystem.js")" type="text/javascript"></script>
    @RenderSection("JavaScript", false)
</head>
<body>
    <div class="container-fluid">
        <header>
            <!--<h1>Система бюджетування</h1>-->
            <div class="navbar navbar-inverse">
                <div class="navbar-inner">
                    @Html.ActionLink("Система бюджетування", "Index", "Home", null, new { @class = "brand" })
                    <ul class="nav">
                        <li>@Html.ActionLink("Аналітика", "Index", "Home")</li>
                        <li class="dropdown">
                            <a id="managementMenu" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">Управління <b class="caret"></b></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="managementMenu">
                                <li>@Html.ActionLink("Центри фінансової відповідальності", "Index", "FinancialCenters")</li>
                                <!--<li>@Html.ActionLink("Співробітники", "Index", "Employees")</li>-->
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a id="budgetMenu" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                Бюджетування <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="budgetMenu">
                                <li>@Html.ActionLink("Активні бюджети", "Index", "ActiveBudgets")</li>
                                <li>@Html.ActionLink("Затвердженні бюджети", "Index", "ApprovalBudgets")</li>
                                <li>@Html.ActionLink("Бюджетний архів", "Index", "BudgetArchive")</li>
                                <li>@Html.ActionLink("Проекти на затвердження","Index", "WaitApproveBudgets")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Довідники", "Index", "BudgetCategoryInfo")</li>
                        <li>@Html.ActionLink("Інформація", "About", "Home")</li>
                    </ul>
                    <div class="navbar-form pull-right">
                        @Html.Partial("_LogOnPartial")
                    </div>
                </div>
            </div>

        </header>
        <section>
            @RenderBody()
        </section>
        <footer>
            <br/>
            <br/>
            <br/>
            <br/>
        </footer>
    </div>
</body>
</html>

Budget.Web/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <span class="text-info">Вітаємо <strong>@User.Identity.Name</strong>!
    @Html.ActionLink("[Вийти]", "LogOff", "Account", null,  new { @class = "btn btn-inverse" }) </span>
}
else {
    @: @Html.ActionLink("Ввійти", "LogOn", "Account", null,  new { @class = "btn btn-inverse" }) 
}